---
title: "UN_Voting"
output: html_document
date: "2022-12-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/R/UN_Voting")
```

```{r}
library(dplyr)
library(tidyverse)
library(readr)
library(ggplot2)
```

```{r}
UN_voting <- read_csv("https://dataverse.harvard.edu/api/access/datafile/6358426")

write_csv(UN_voting, "~/R/UN_Voting/data/UN_voting.csv")
```

```{r}
# Analyze "aggreableness" of UN decisions by year

voting_per_year <- UN_voting %>%
  group_by(year) %>%
  summarize(total = n(),
            percent_yes = mean(vote == 1))
```

```{r}
# By country 

voting_by_country <- UN_voting %>%
  group_by(Countryname) %>%
  summarize(total = n(),
            percent_yes = mean(vote ==1))
```

```{r}
# By country and year
voting_by_country_year <- UN_voting %>%
  group_by(year, Countryname) %>%
  summarize(total = n(),
            percent_yes = mean(vote ==1))
```

```{r}
# Sort in ascending order of percent_yes
voting_by_country %>%
  arrange(percent_yes)

# Now sort in descending order
voting_by_country %>%
  arrange(desc(percent_yes))

# Filter out countries with fewer than 100 votes
voting_by_country %>%
  arrange(percent_yes) %>%
  filter(total >= 100)
```

```{r}
# Filter for 2020
UN_voting_2020 <- UN_voting %>%
  filter(year == 2020)

UN_voting_2020

#Filter for 2021
countries_2021 <- UN_voting %>%
  group_by(year, Country, Countryname) %>%
  filter(year == 2021) %>%
  summarize(total = n(),
            percent_yes = mean(vote == 1)) %>%
  rename(iso3 = Country)
```

